class User < ActiveRecord::Base
#  establish_connection :xuexi
  #   用户类型
  #	 普通用户 （教育局其他用户）
  USER_TYPE_USER = 0
  #	教师 1
  USER_TYPE_TEACHER = 1
  #	学生 2
  USER_TYPE_STUDENT = 2
  #	// 家长 3
  USER_TYPE_PARENT = 3
  #	// 员工
  USER_TYPE_EMPLOYEE = 4;

  #未开
	USER_STATUS_NONE = 10
	#申请退订
	USER_STATUS_CANCEL_APPLICATION = 15
	#免费
	USER_STATUS_FREE = 20
	#稽核
	USER_STATUS_AUDIT = 21
	#申请免费
	USER_STATUS_FREE_APPLICATION = 25
	#收费
  USER_STATUS_CHARGE = 30
	#申请收费
	USER_STATUS_CHARGE_APPLICATION = 35
	#删除
	USER_STATUS_DELETED = 40
	#申请删除
	USER_STATUS_DELETED_APPLICATION = 45
	#收费换号中
	USER_STATUS_CHARGE_REPLACING_NUMBER = 50
	#一元附号
	USER_STATUS_CHARGE_ONE_YUAN = 61
	#活动
	USER_STATUS_ACTIVITY = 62
	#特免
  USER_STATUS_SPECIAL_FREE = 63
	#投诉号码
	USER_STATUS_COMPLAIN_NUMBER = 64
	#外地号码
	USER_STATUS_ECDEMIC = 65
	#错误号码
	USER_STATUS_WRONG_NUMBER = 66
	#销户号码
	USER_STATUS_STOPED_NUMBER = 67
	#运营商屏蔽号码
	USER_STATUS_BLACKLIST_NUMBER = 68
	#状态转换中
	USER_STATUS_CONVERTING = 70

end

